version: 2
updates:

  # Maintain dependencies for GitHub Actions in root workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions in http_api template
  - package-ecosystem: "github-actions"
    directory: "/http_api/templates"
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions in package template
  - package-ecosystem: "github-actions"
    directory: "/package/templates"
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions in telegram_bot template
  - package-ecosystem: "github-actions"
    directory: "/telegram_bot/templates"
    schedule:
      interval: "weekly"
